version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: bun
    schedule:
      interval: weekly
    groups:
      version:
        applies-to: version-updates
        update-types:
          - patch
          - minor
          - major
